name: tests

on: 
    push:
        branches:
            - master

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: ['8.1','8.2','8.3']
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v4"
        
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # PHP Extras
          coverage: none
          tools: composer, phpunit:8.5
          ini-values: "memory_limit=512M"
          # extensions: ${{ matrix.ffi }}

      - name: setup OpenBLAS
        run: |
          sudo apt update
          sudo apt install libopenblas-dev
          sudo apt install liblapacke-dev

      - name: Download rindow-matlib
        run: |
          ( cd .. && git clone https://github.com/rindow/rindow-matlib )
          ( cd ../rindow-matlib && git checkout 1.0.0 )
          ( cd ../rindow-matlib && cmake -S . -B build )

      - name: Build
        run: |
          composer update
          phpize${{ matrix.php }}
          ./configure --enable-rindow_openblas --with-rindow_matlib=../rindow-matlib --with-php-config=php-config${{ matrix.php }}
          make clean
          make

      - name: Install rindow_openblas
        run: |
          sh ./packaging.sh ${{ matrix.php }}
          RINDOW_OPENBLAS_VERSION=`fgrep "# define PHP_RINDOW_OPENBLAS_VERSION" php_rindow_openblas.h | cut -d " " -f 4 | cut -d "\"" -f 2`
          . /etc/os-release
          sudo apt install -y ./rindow-openblas-php${{ matrix.php }}_${RINDOW_OPENBLAS_VERSION}-1+${ID}${VERSION_ID}_amd64.deb

      - name: Tests
        run: |
          phpunit -c phpunit


